#!/bin/bash

set -e

PLATFORM=$(uname)
DEST="/Library/Frameworks"

# Get optional destination directory
if [ "$#" -gt 0 ]; then
    DEST="$1"
fi

if [[ "$PLATFORM" == "Darwin" || "$TRAVIS_OS_NAME" == "osx" ]]; then
    echo "Installing SDL2"
    wget --show-progress https://www.libsdl.org/release/SDL2-2.0.5.dmg
    hdiutil attach SDL2-2.0.5.dmg
    cp -r -n /Volumes/SDL2/*.framework "$DEST"
    hdiutil detach /Volumes/SDL2
    rm SDL2-2.0.5.dmg

    echo "Installing SDL image"
    wget --show-progress https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.1.dmg
    hdiutil attach SDL2_image-2.0.1.dmg
    cp -r -n /Volumes/SDL2_image/*.framework "$DEST"
    hdiutil detach /Volumes/SDL2_image/
    rm SDL2_image-2.0.1.dmg

    echo "Installing SDL mixer"
    wget --show-progress https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.1.dmg
    hdiutil attach SDL2_mixer-2.0.1.dmg
    cp -r -n /Volumes/SDL2_mixer/*.framework "$DEST"
    hdiutil detach /Volumes/SDL2_mixer/
    rm SDL2_mixer-2.0.1.dmg
fi
#TODO: install dependencies for windows and linux!
