#!/bin/bash
# This script converts Diamond key:value config files to JSON.

# Exit if there's an error
set -e

# Check arguments
if [ "$#" -lt 1 ]; then
    echo "Usage: diamondtojson filename"
    exit 1
fi

FILE="$1"
# the delimiter used to separate keys and values in the input file
SEP=":"

# Add JSON outer brackets,
# remove comments and empty lines,
# add tab spaces, quotations, and comma to each line,
# and remove comma from last line.
echo "{"
sed -e '/^#/d' \
    -e '/^$/d' \
    "$FILE" \
    | awk -F ""$SEP"[[:space:]]+" -v sep="$SEP" '$2 !~ /[0-9]/ && $2 !~ /[Tt]rue/ && $2 !~ /[Ff]alse/ {printf "%s%s \"%s\"\n", $1, sep, $2;next}{print}' \
    | awk -F ""$SEP"" -v sep="$SEP" '{printf "    \"%s\"%s%s,\n", $1, sep, $2}' \
    | sed '$s/,$//'
#     -e 's/\(.*\):\(.*\)/    "\1":\2,/'
echo "}"
